FROM jboss/wildfly:latest
ADD target/lab2_4-1.0-SNAPSHOT.war /opt/jboss/wildfly/standalone/deployments/
EXPOSE 8080
#FROM tomcat:latest
#ADD target/lab2_4-1.0-SNAPSHOT.war /Users/Honor/Downloads/apache-tomcat-8.5.97-windows-x64/webapps
